USE [Advent]
GO

-- Third-Party Administrator
INSERT INTO [Company] ([Name], [CountryId], [TPA], [CreatedDTO], [CreatedById], [UpdatedDTO], [UpdatedById])
SELECT
 [Name] = N'Advent Solutions Management Ltd',
	[CountryId] = N'GB',
	[TPA] = 1,
	[CreatedDTO] = N'2015-05-01',
	[CreatedById] = usr.[Id],
	[UpdatedDTO] = N'2015-05-01',
	[UpdatedById] = usr.[Id]
FROM [User] usr
WHERE usr.[Email] = N'pierre@whitespace.co.uk'
GO

-- Coverholder
INSERT INTO [Company] ([Name], [CountryId], [COV], [CreatedDTO], [CreatedById], [UpdatedDTO], [UpdatedById])
SELECT
 [Name] = cov.[Name],
	[CountryId] = N'GB',
	[COV] = 1,
	[CreatedDTO] = N'2015-05-01',
	[CreatedById] = usr.[Id],
	[UpdatedDTO] = N'2015-05-01',
	[UpdatedById] = usr.[Id]
FROM [User] usr
 CROSS APPLY (VALUES
	  (N'Avantia Insurance Limited'),
			(N'B J Fields'),
			(N'C C Insurance Limited'),
			(N'Darlington Building Society')
	 ) cov ([Name])
WHERE usr.[Email] = N'pierre@whitespace.co.uk'
GO

-- Lloyd's Broker
INSERT INTO [Company] ([Name], [CountryId], [LBR], [CreatedDTO], [CreatedById], [UpdatedDTO], [UpdatedById])
SELECT
 [Name] = lbr.[Name],
	[CountryId] = N'GB',
	[LBR] = 1,
	[CreatedDTO] = N'2015-05-01',
	[CreatedById] = usr.[Id],
	[UpdatedDTO] = N'2015-05-01',
	[UpdatedById] = usr.[Id]
FROM [User] usr
 CROSS APPLY (VALUES
   (N'AAA Insurance & Reinsurance Brokers Ltd'),
   (N'AEC Master Brokers S.r.l'),
   (N'AFL Insurance Brokers Ltd'),
   (N'Afro-Asian Insurance Services Limited'),
   (N'Alsford Page & Gems Ltd'),
   (N'Alston Gayler & Co Ltd'),
   (N'Alwen Hough Johnson Ltd'),
   (N'Anglo Pacific Consultants (London) Ltd'),
   (N'Aon Benfield'),
   (N'Aon Benfield Iberia Correduria de Reaseguros S.A.U.'),
   (N'Aon Benfield Italia S.p.A'),
   (N'Aon Ltd'),
   (N'Aquaduct Underwriting Limited'),
   (N'ARB International Ltd'),
   (N'Arthur J Gallagher Insurance Brokers Ltd'),
   (N'Arthur J Gallagher Ltd'),
   (N'Arx Insurance Brokers Ltd'),
   (N'Bannerman Rendell Ltd'),
   (N'BDB Ltd'),
   (N'Beach & Associates Ltd'),
   (N'Bell & Clements Ltd'),
   (N'Bennett Gould & Partners Ltd'),
   (N'Berry Palmer & Lyle Ltd'),
   (N'Besso Ltd'),
   (N'Bluefin Insurance Services Ltd'),
   (N'BMG Insurance Brokers Ltd'),
   (N'BMS Group'),
   (N'Boston Marks Insurance Brokers (London) Ltd'),
   (N'Butcher Robinson & Staples International Ltd'),
   (N'Butcher Robinson Staples Ltd'),
   (N'Butcher Robinson Staples Marine Limited'),
   (N'C J Coleman & Co Ltd'),
   (N'Carroll & Partners Ltd'),
   (N'Carroll Insurance Group Ltd'),
   (N'CBC Ltd'),
   (N'CGNMB LLP (Cooper Gay & Co Ltd)'),
   (N'CGNMB LLP (Newman Martin & Buchan)'),
   (N'Challenge Group Brokers (UK) Ltd'),
   (N'Channing Lucas & Partners'),
   (N'Chesterfield Insurance Brokers Ltd'),
   (N'Citynet Insurance Brokers Ltd'),
   (N'CK Re Ltd'),
   (N'Cogent Resources Ltd'),
   (N'Coleman Ambris LLP'),
   (N'Colemont Insurance Brokers Limited'),
   (N'Contractsure Limited'),
   (N'Cooper Gay France SASU'),
   (N'Corrie Bauckham Batts Ltd'),
   (N'Cosmos Services Company Ltd (UK Branch)'),
   (N'Crispin Speers & Partners Ltd'),
   (N'Croton Stokes Wilson Holden Limited'),
   (N'Dashwood Brewer & Phipps Ltd'),
   (N'Decus Insurance Brokers Ltd'),
   (N'Direct Insurance Brokers PLC'),
   (N'EBA Insurance Services Ltd'),
   (N'EC3 Brokers Limited'),
   (N'Edge Brokers (London) Ltd'),
   (N'Ellis Clowes & Company Limited'),
   (N'Endeavour Insurance Services Limited'),
   (N'European Specialty Risks Ltd'),
   (N'Faber Global Limited'),
   (N'FP Marine Risks Limited'),
   (N'Genesis Insurance Brokers Limited'),
   (N'Griffiths & Armour Global Risks Ltd'),
   (N'Grimme Butcher Jones Ltd'),
   (N'Grosvenor Brokers (America) LLC'),
   (N'Guest Krieger Ltd'),
   (N'H W Wood Ltd'),
   (N'Harman Kemp North America Ltd'),
   (N'HBA Ltd'),
   (N'Houlder Insurance Services Ltd'),
   (N'Howard Global Insurance Services Limited'),
   (N'Howden Insurance Brokers'),
   (N'Independent Broking Solutions Ltd'),
   (N'Ink Underwriting Agencies Limited'),
   (N'Integro Insurance Brokers Ltd'),
   (N'Iris Insurance Brokers Ltd'),
   (N'J B Boda & Co (UK) Ltd'),
   (N'James Hampden International Insurance Brokers Ltd'),
   (N'JLT Reinsurance Brokers Ltd'),
   (N'JLT Specialty Limited '),
   (N'John Holman & Sons Ltd'),
   (N'K M Dastur & Co Ltd'),
   (N'Kite Warren & Wilson Ltd'),
   (N'Lime Street Insurance Brokers Limited'),
   (N'Lloyd & Partners Limited'),
   (N'Lochain Patrick Insurance Brokers '),
   (N'Lockton Companies LLP'),
   (N'Lockton MENA Limited'),
   (N'Lonmar Global Risks Limited'),
   (N'Lonsdale Insurance Brokers Ltd'),
   (N'Lothbury UK Ltd'),
   (N'Lucas Fettes & Partners Ltd'),
   (N'MAR Risk Services Ltd'),
   (N'Marine Aviation & General (London) Ltd'),
   (N'Market Insurance Brokers Ltd'),
   (N'Marsh Brokers Limited'),
   (N'Marsh Ltd'),
   (N'Max Insurance Brokers Ltd'),
   (N'Meridian Risk Solutions Ltd'),
   (N'MGB Insurance Brokers Ltd'),
   (N'Miles Smith Broking Ltd'),
   (N'Miller Insurance Services LLP'),
   (N'Nausch, Hogan & Murray (UK)'),
   (N'NBJ London Markets Ltd'),
   (N'Nuytten Verzekeringen N.V.'),
   (N'Oxford Insurance Brokers Ltd'),
   (N'Oxygen Insurance Brokers Ltd'),
   (N'Paragon International Insurance Brokers'),
   (N'Paul Napier Ltd'),
   (N'Price Forbes & Partners Ltd'),
   (N'PRO Insurance Solutions Limited'),
   (N'R K Harrison Group Limited'),
   (N'R L Davison & Co Ltd'),
   (N'R&Quiem Limited'),
   (N'Ramon International Insurance Brokers Ltd'),
   (N'RFIB Group Limited'),
   (N'Riva Insurance Brokers Limited'),
   (N'Roanoke International Brokers Limited'),
   (N'Robertson Taylor Insurance Brokers Ltd'),
   (N'Ropner Insurance Services Ltd'),
   (N'Safeonline LLP'),
   (N'Seascope Insurance Services Ltd'),
   (N'Senior Wright Ltd'),
   (N'Shepherd Compello Ltd'),
   (N'Smith Bilbrough & Co Ltd'),
   (N'Special Contingency Risks Ltd'),
   (N'Speedwell Insurance Brokers Ltd'),
   (N'SSL Insurance Brokers Ltd'),
   (N'Strategic Insurance Services Ltd'),
   (N'Texel Finance Ltd'),
   (N'THB Group Ltd'),
   (N'The Underwriting Exchange Ltd'),
   (N'Thistle Insurance Services Limited'),
   (N'TigerRisk (UK) Ltd'),
   (N'Tobell Insurance Services Ltd'),
   (N'Tysers & Co Ltd'),
   (N'United Insurance Brokers Ltd'),
   (N'W T Butler & Co Ltd'),
   (N'Willis Ltd')
	 ) lbr ([Name])
WHERE usr.[Email] = N'pierre@whitespace.co.uk'
GO

UPDATE [Company] SET [CAR] = 1 WHERE [Name] LIKE N'%underwrit%'
GO